import { useEffect } from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useDispatch, useSelector } from 'react-redux';
import { fetchTodos } from '@/redux/slices/todo';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const dispatch = useDispatch();
  const { isLoading, data, isError } = useSelector((state) => state.todo);
  useEffect(() => {
    dispatch(fetchTodos());
  }, []);
  if (isLoading) {
    return 'Loding';
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        {data && data.map(({ title, id }) => <p key={id}>{title}</p>)}
      </main>
    </>
  );
}
